CREATE DATABASE IF NOT EXISTS art_space;

USE art_space;

SHOW TABLES;

CREATE TABLE IF NOT EXISTS art_users (
	id BIGINT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(150) NOT NULL UNIQUE,
    password_hash VARCHAR(100) NOT NULL,
    role VARCHAR(20) NOT NULL
) ENGINE = InnoDB;